### ISSUE TITLE
books: rule 084__2 subject_classification

### ISSUE THREAD

**Issue by equadon** [CERNDocumentServer/cds-dojson#207]
Possible values for `084__2`:
```
CERN Yellow Report
CERN Library
rvk
bisacsh
PACS
```
Just to verify: `CERN Yellow Report`, `CERN Library`, and `PACS` will become keywords while `rvk` and `bisacsh` will update the `subject_classification` schema to `ICS`. Is this the correct behavior?

**Comment by agentilb** [comment]
Hi @equadon, 

As far as I know, it is not necessary to keep: 084 "CERN Yellow Report" because the value is already in 088. I believe this info is used for the sorting in the collection.. 
Same applies for  "CERN Library".
Please do not add those values to keywords, those are report numbers already stored in another field. 

When PACS, it should indeed be in the keywords. 

Can you let me know the records with bisacsh and rvk, I don't find them in the Books and Proceedings collection? 

Anne

**Comment by kprzerwa** [comment]
HI @agentilb! We have found those values by searching in the possible values in field 084 of all the records fullfilling the query:
690C_:BOOK OR 690C_:STANDARD OR 690C_:"YELLOW REPORT" OR 690C_:BOOKSUGGESTION OR 980__:PROCEEDINGS OR 980__:PERI OR 697C_:LEGSERLIB OR 697C_:"ENGLISH BOOK CLUB" -980__:DELETED

**Comment by agentilb** [comment]
Hi @kprzerwa  Do you have examples of records? Thanks!

**Comment by kprzerwa** [comment]
@equadon can you provide examples?

**Comment by kprzerwa** [comment]
question asked to the Library, closing as stale
