### ISSUE TITLE
update schemas

### ISSUE THREAD

**Issue by kprzerwa** [CERNDocumentServer/cds-dojson#224]
- document
- item
- eitem
- series
- keywords
- locations
- etc -  check with invenio-app-ils for the reference

**Comment by kprzerwa** [comment]
@agentilb I have some question about schemas:
1. which fields in the electronic item would be required?
2. dois field exists in the document, item and electronic item. Is it correct? If yes what is the reason for which we keep the dois in the document level? Shall we have them in the multipart monographs too? 
3. there is a note
   ``` If the book series has a Journal record,
                `hep.json#/properties/publication_info` should be used
                instead.
   ``` 
does it mean that sometimes journal is stored as a series in 490?

**Comment by agentilb** [comment]
@kprzerwa 
1. I guess the only field which is mandatory will be URL or DOI, one of those have to be filled. (see below)
2. Indeed DOI exists at the document level, because we said it is an identifier of the document and it makes sense to keep it there. Actually, what we said during a discussion with Nicola that in the e-item, the DOI is used for the linking to the Fulltext. So what we can do to simplify is the keep the DOI at the document level in the specific field, and in the e-item have only the field URL that will be either a DOI or a normal URL. What do you think? 
I don't see any example where there is a DOI for multi-volume monographs. 
3.  No, this comment comes from the Inspire model. You can just remove. 

I will review the other changes you did and let you know if I have some comments.
