### ISSUE TITLE
Record type queries

### ISSUE THREAD

**Issue by kprzerwa** [CERNDocumentServer/cds-dojson#235]
Updated in
https://codimd.web.cern.ch/LV-Ran4pTym4szE8sL0Fqw

**Comment by agentilb** [comment]
Hi Here are some of the queries requested: 

All Books (excluding yellow reports)
690C:BOOK -690C:YELLOW REPORT

All Proceedings (excluding yellow reports)
690C:PROCEEDINGS -690C:YELLOW REPORT

Note: I exclude the YR for the time being because some are BOOKs, some are PROCEEDINGS and some are other types... I'm working on harmonising this. 

All standards
690C:STANDARD

- Documents belonging to a Book series: 
Add 490:'*'

- All records having keywords: 
add 6531_:'*'

For the multi-volumes, I'm still working on it. This is such a mess, I'm trying to find a way to make it simple.

**Comment by agentilb** [comment]
For the Multi-volumes books, the query should be: 
690C:BOOK (246__n:'*' or 246__p)  -690C:YELLOW REPORT 

Volume title: 246__p
Volume number: 246__ n
Main document title: 245__ 

In many cases, we have all the volumes in a single record: 
ex: https://cds.cern.ch/record/1634843?ln=en

I other cases, we have the volumes catalogued separately. 
https://cds.cern.ch/search?ln=en&p=001%3A98416+or+001%3A98417&action_search=Search&op1=a&m1=a&p1=&f1=&c=CERN+Document+Server&sf=&so=d&rm=&rg=100&sc=1&of=hb

Is there a way to have a script that would find the volumes that go together? 
-> the 245 should be identical, as well as the publisher. 
-> publishing year and authors are similar in many cases, but might differ as well. 

If it is too combersome to script this, we'll find a way to do it on our side.
